apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: names-cluster
spec:
  kafka:
    replicas: 3
    listeners:
      - name: plain
        type: internal
        port: 9092
        tls: false
      - name: tls
        type: internal
        port: 9093
        tls: true
      - name: external
        type: route
        port: 9094
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}